name: Build and Deploy HARAKA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [frontend-updated]

env:
  DOCKER_IMAGE: omarzakaria10/haraka
  FRONTEND_REPO: OmarZakaria10/HARAKA-ReactJS

jobs:
  # Backend preparation job
  prepare-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Backend Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Backend Dependencies
      run: npm ci
      
    - name: Run Backend Tests
      run: |
        echo "Running backend tests..."
        # npm test
        
    - name: Cache Backend Dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-backend-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

  # Frontend preparation job (runs in parallel)
  prepare-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Frontend Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.FRONTEND_REPO }}
        path: frontend-temp
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend-temp/package-lock.json
        
    - name: Install Frontend Dependencies
      working-directory: frontend-temp
      run: npm ci
      
    - name: Build Frontend
      working-directory: frontend-temp
      run: |
        CI=false npm run build
        
    - name: Upload Frontend Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend-temp/build/
        retention-days: 1

  # Build and deploy job (depends on both previous jobs)
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [prepare-backend, prepare-frontend]
    
    steps:
    - name: Checkout Backend Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Restore Backend Dependencies Cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-backend-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-
          
    - name: Install Backend Dependencies (if cache miss)
      run: npm ci
      
    - name: Download Frontend Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: build/
        
    - name: Verify Frontend Build
      run: |
        ls -la build/
        echo "Frontend build successfully integrated!"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example: kubectl rollout restart deployment/haraka-backend
