name: Trigger Backend Build

on:
  push:
    branches: [main]

jobs:
  trigger-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "🔍 Triggering backend build from frontend push"
          echo "Frontend repo: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"

      - name: Trigger Backend Build
        run: |
          echo "🚀 Sending dispatch to backend repository..."

          # Check if secret exists
          if [ -z "${{ secrets.BACKEND_TRIGGER_TOKEN }}" ]; then
            echo "❌ Error: BACKEND_TRIGGER_TOKEN secret not found"
            echo "Please add this secret in your repository settings:"
            echo "https://github.com/OmarZakaria10/HARAKA-ReactJS/settings/secrets/actions"
            exit 1
          fi

          # Send repository dispatch
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BACKEND_TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OmarZakaria10/HARAKA-ExpressJS/dispatches \
            -d '{
              "event_type": "frontend-updated",
              "client_payload": {
                "frontend_sha": "${{ github.sha }}",
                "frontend_ref": "${{ github.ref }}",
                "frontend_actor": "${{ github.actor }}"
              }
            }'

          echo "✅ Repository dispatch sent successfully"
