name: Trigger Backend Build

on:
  push:
    branches: [ main ]  # When someone pushes to frontend main branch
  pull_request:
    branches: [ main ]
    types: [ closed ]   # When PR is merged to main

jobs:
  trigger-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Trigger Backend Workflow
      run: |
        echo "Triggering backend build for frontend changes..."
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.BACKEND_TRIGGER_TOKEN }}" \
          https://api.github.com/repos/OmarZakaria10/HARAKA-Future_OF_Egypt/dispatches \
          -d '{"event_type":"frontend-updated", "client_payload": {"frontend_ref": "${{ github.ref }}", "frontend_sha": "${{ github.sha }}", "frontend_actor": "${{ github.actor }}"}}'
          
    - name: Notify success
      if: success()
      run: echo "Backend build triggered successfully"
      
    - name: Notify failure
      if: failure()
      run: |
        echo "Failed to trigger backend build"
        exit 1
